### ISSUE TITLE
Multiples mode does not seem to work

### ISSUE THREAD

**Issue by mountaindude** [brianbooden/StackedMultiples#1]
Using the app on my own data set, which is a few thousand points, but nothing too large.
There is no change when clicking the "multiples" option box, the bars are still stacked. 
Haven't really dug further into it than that.. love the concept though, so happy to help sorting things out if I can.

**Comment by brianbooden** [comment]
Hey Goran, can you Ctrl+Shift+Right Click for me and give me the Console error from Show DevTools in QS Desktop?  I tested 3 or 4 data sets.  In terms of troubleshooting - any way you could knock out negative values as a starting point?

Edit: Also, can you check that you're clicking completely on the radio and not the text?  Sometimes this seems to be a bit buggy.

**Comment by brianbooden** [comment]
@mountaindude I have updated the listeners so that clicking on the label triggers the radio also.  Give it a try and let me know if this resolves.

**Comment by brianbooden** [comment]
@mountaindude I'm pretty sure this is resolved now based on others feedback, so closing.

**Comment by mountaindude** [comment]
@brianbooden confirmed - working now. Ace!
